Add support for coffeescript versions 1 and 2.

diff --git a/script/build-source-gem b/script/build-source-gem
--- a/script/build-source-gem
+++ b/script/build-source-gem
@@ -28,7 +28,19 @@ npm install
 mkdir -p lib/coffee_script
 
 MINIFY=false ./bin/cake build:browser
-mv docs/v2/browser-compiler/coffeescript.js lib/coffee_script/coffee-script.js
+
+case "$VERSION" in
+1.*)
+  mv docs/v1/browser-compiler/coffee-script.js lib/coffee_script/coffee-script.js
+  ;;
+2.*)
+  mv docs/v2/browser-compiler/coffeescript.js lib/coffee_script/coffee-script.js
+  ;;
+*)
+  echo "NO VALID VERSION DETECTED. FAILING HARD."
+  exit 1
+  ;;
+esac
 
 cat << ERUBY > lib/coffee_script/source.rb
 module CoffeeScript
